package bkc

import "strings"

func init() {
	register(
		// Qwen3 dense small checkpoints — fit almost any consumer/workstation GPU.
		qwenSmallDense("qwen3-0-6b", "Qwen3 0.6B", "Qwen/Qwen3-0.6B", 6),
		qwenSmallDense("qwen3-1-7b", "Qwen3 1.7B", "Qwen/Qwen3-1.7B", 8),
		qwenSmallDense("qwen3-4b", "Qwen3 4B", "Qwen/Qwen3-4B", 12),
		qwenSmallDense("qwen3-8b", "Qwen3 8B", "Qwen/Qwen3-8B", 20),
		qwenSmallDense("qwen3-14b", "Qwen3 14B", "Qwen/Qwen3-14B", 32),
		qwenSmallDense("qwen3-32b", "Qwen3 32B", "Qwen/Qwen3-32B", 72),

		// Qwen3-30B-A3B dense MoE (A3B active).
		Config{
			ID:       "qwen3-30b-a3b",
			Name:     "Qwen3 30B A3B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-30B-A3B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
				"--max-model-len 131072",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3 30B A3B MoE, single-GPU Hopper/Blackwell default.",
			Source:          "vllm-project/recipes Qwen/Qwen3.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceA100_80, DeviceGB10},
			MinVRAMGBPerGPU: 64,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3 235B A22B BF16 (4x TP per the recipe).
		Config{
			ID:       "qwen3-235b-a22b",
			Name:     "Qwen3 235B A22B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-235B-A22B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"-tp 4",
				"--disable-log-requests",
				"--swap-space 32",
				"--distributed-executor-backend mp",
				"--max-num-batched-tokens 32768",
				"--max-model-len 32768",
				"--no-enable-prefix-caching",
				"--gpu-memory-utilization 0.8",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3 235B A22B on 4xH200/B200.",
			Source:          "vllm-project/recipes Qwen/Qwen3.md",
			TargetDevices:   []string{DeviceH200, DeviceB200, DeviceH100_94},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3 235B A22B FP8.
		Config{
			ID:       "qwen3-235b-a22b-fp8",
			Name:     "Qwen3 235B A22B FP8",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-235B-A22B-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"-tp 4",
				"--disable-log-requests",
				"--swap-space 16",
				"--distributed-executor-backend mp",
				"--max-num-batched-tokens 32768",
				"--max-model-len 32768",
				"--no-enable-prefix-caching",
				"--gpu-memory-utilization 0.8",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3 235B A22B FP8 on 4x Hopper/Blackwell GPUs.",
			Source:          "vllm-project/recipes Qwen/Qwen3.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Qwen3-Next 80B A3B Instruct BF16.
		Config{
			ID:       "qwen3-next-80b-a3b",
			Name:     "Qwen3-Next 80B A3B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-Next-80B-A3B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 4",
				"--served-model-name qwen3-next",
				"--enable-prefix-caching",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3-Next 80B A3B on 4x Hopper/Blackwell GPUs.",
			Source:          "vllm-project/recipes Qwen/Qwen3-Next.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3-Next 80B A3B Instruct FP8.
		Config{
			ID:       "qwen3-next-80b-a3b-fp8",
			Name:     "Qwen3-Next 80B A3B Instruct FP8",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-Next-80B-A3B-Instruct-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 4",
				"--enable-prefix-caching",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "FP8 Qwen3-Next 80B on 4x Hopper/Blackwell GPUs.",
			Source:          "vllm-project/recipes Qwen/Qwen3-Next.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 40,
			MinGPUCount:     2,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Qwen3-Coder 480B A35B — 8x TP expert-parallel.
		Config{
			ID:       "qwen3-coder-480b-a35b",
			Name:     "Qwen3-Coder 480B A35B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-Coder-480B-A35B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--max-model-len 32000",
				"--enable-expert-parallel",
				"--tensor-parallel-size 8",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Flagship coding MoE on 8x Hopper or Blackwell.",
			Source:          "vllm-project/recipes Qwen/Qwen3-Coder-480B-A35B.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3-VL 235B A22B Instruct BF16.
		Config{
			ID:       "qwen3-vl-235b-a22b",
			Name:     "Qwen3-VL 235B A22B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-VL-235B-A22B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 8",
				"--mm-encoder-tp-mode data",
				"--async-scheduling",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3-VL 235B A22B Instruct on 8x Hopper/Blackwell GPUs.",
			Source:          "vllm-project/recipes Qwen/Qwen3-VL.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3-VL 235B A22B Instruct FP8.
		Config{
			ID:       "qwen3-vl-235b-a22b-fp8",
			Name:     "Qwen3-VL 235B A22B Instruct FP8",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-VL-235B-A22B-Instruct-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 4",
				"--limit-mm-per-prompt.video 0",
				"--async-scheduling",
				"--gpu-memory-utilization 0.95",
				"--max-num-seqs 128",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "FP8 Qwen3-VL 235B, tensor-parallel 4 image-only.",
			Source:          "vllm-project/recipes Qwen/Qwen3-VL.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Qwen2.5-VL 7B.
		Config{
			ID:       "qwen2-5-vl-7b",
			Name:     "Qwen2.5-VL 7B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen2.5-VL-7B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
				"--max-model-len 32768",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen2.5-VL 7B Instruct — single-GPU default.",
			Source:          "vllm-project/recipes Qwen/Qwen2.5-VL.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 24,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen2.5-VL 72B BF16 (TP=4).
		Config{
			ID:       "qwen2-5-vl-72b",
			Name:     "Qwen2.5-VL 72B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen2.5-VL-72B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 4",
				"--max-model-len 32768",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen2.5-VL 72B on 4x 80 GB GPUs per NVIDIA's recipe.",
			Source:          "vllm-project/recipes Qwen/Qwen2.5-VL.md",
			TargetDevices:   []string{DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     2,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
			Notes: []string{
				"TP should be >= 2 on 80 GB GPUs to avoid OOM.",
			},
		},

		// Qwen3-ASR.
		Config{
			ID:       "qwen3-asr-1-7b",
			Name:     "Qwen3-ASR 1.7B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-ASR-1.7B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 1",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Compact Qwen3 ASR deployable on a single 16 GB+ GPU.",
			Source:          "vllm-project/recipes Qwen/Qwen3-ASR.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 16,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3Guard-Gen 0.6B.
		Config{
			ID:       "qwen3guard-gen-0-6b",
			Name:     "Qwen3Guard-Gen 0.6B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3Guard-Gen-0.6B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--host 0.0.0.0",
				"--max-model-len 32768",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Guardrails generator — runs on any modern NVIDIA/AMD GPU.",
			Source:          "vllm-project/recipes Qwen/Qwen3Guard-Gen.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 8,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3.6 35B A3B.
		Config{
			ID:       "qwen3-6-35b-a3b",
			Name:     "Qwen3.6 35B A3B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3.6-35B-A3B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 8",
				"--max-model-len 262144",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3.6 35B A3B on 8x Hopper/Blackwell (per the Qwen3.5 recipe).",
			Source:          "vllm-project/recipes Qwen/Qwen3.5.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3.6 27B VLM NVFP4 compressed-tensors baseline (Blackwell).
		Config{
			ID:       "qwen3-6-27b-nvfp4",
			Name:     "Qwen3.6-27B",
			Workload: WorkloadVLLM,
			ModelID:  "sakamakismile/Qwen3.6-27B-NVFP4",
			Image:    imageVLLMCU130_019,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--served-model-name Qwen3.6-27B",
				"--tensor-parallel-size 1",
				"--max-model-len 262144",
				"--max-num-seqs 2",
				"--kv-cache-dtype fp8",
				"--gpu-memory-utilization 0.90",
				"--limit-mm-per-prompt {\"image\":4,\"video\":0}",
				"--reasoning-parser qwen3",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_xml",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Compressed-tensors NVFP4 Qwen3.6 27B VLM on a single RTX PRO 6000 Blackwell; serves as Qwen3.6-27B with image input enabled.",
			Source:          "Hugging Face sakamakismile/Qwen3.6-27B-NVFP4 model card",
			TargetDevices:   []string{DeviceRTXPRO6000, DeviceB200},
			MinVRAMGBPerGPU: 96,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Do not pass --quantization modelopt; this repo declares compressed-tensors in its model config.",
				"Uses the model card's production launch: 256K context, FP8 KV cache, max-num-seqs 2, and gpu-memory-utilization 0.90.",
				"Keeps image input enabled with an explicit multimodal prompt limit.",
				"Enables qwen3_xml tool calling for Qwen3.6 chat templates.",
				"The model card notes faster modelopt + MTP siblings exist, but this BKC intentionally targets this exact compressed-tensors repo.",
			},
		},

		// Qwen3.6 27B Text NVFP4 + MTP (Blackwell).
		Config{
			ID:       "qwen3-6-27b-text-nvfp4-mtp",
			Name:     "Qwen3.6-27B Text NVFP4 MTP",
			Workload: WorkloadVLLM,
			ModelID:  "sakamakismile/Qwen3.6-27B-Text-NVFP4-MTP",
			Image:    imageVLLMCU130_019,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--quantization modelopt",
				"--language-model-only",
				"--tensor-parallel-size 1",
				"--max-model-len 262144",
				"--max-num-seqs 2",
				"--kv-cache-dtype fp8",
				"--gpu-memory-utilization 0.90",
				"--reasoning-parser qwen3",
				"--speculative-config.method qwen3_5_mtp",
				"--speculative-config.num_speculative_tokens 3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "ModelOpt NVFP4 Qwen3.6 27B text-only checkpoint with Qwen3.5 MTP speculation for single-GPU Blackwell.",
			Source:          "Hugging Face sakamakismile/Qwen3.6-27B-Text-NVFP4-MTP model card",
			TargetDevices:   []string{DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 96,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Uses dotted speculative-config arguments instead of JSON so Yokai passes them as clean argv tokens.",
				"Targets GB10 / DGX Spark, single RTX PRO 6000 Blackwell, and larger Blackwell GPUs.",
			},
		},

		// Qwen3.5 397B A17B FP8.
		Config{
			ID:       "qwen3-5-397b-a17b-fp8",
			Name:     "Qwen3.5 397B A17B FP8",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3.5-397B-A17B-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"-dp 8",
				"--enable-expert-parallel",
				"--language-model-only",
				"--reasoning-parser qwen3",
				"--enable-prefix-caching",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3.5 397B A17B FP8 with data parallel expert routing.",
			Source:          "vllm-project/recipes Qwen/Qwen3.5.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Qwen3.5 397B A17B NVFP4 (Blackwell).
		Config{
			ID:       "qwen3-5-397b-a17b-nvfp4",
			Name:     "Qwen3.5 397B A17B NVFP4",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/Qwen3.5-397B-A17B-NVFP4",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"-dp 4",
				"--enable-expert-parallel",
				"--language-model-only",
				"--reasoning-parser qwen3",
				"--enable-prefix-caching",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "NVFP4 Blackwell deployment of Qwen3.5 397B A17B.",
			Source:          "vllm-project/recipes Qwen/Qwen3.5.md",
			TargetDevices:   []string{DeviceB200},
			MinVRAMGBPerGPU: 180,
			MinGPUCount:     4,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
		},
	)
}

// qwenSmallDense returns a BKC config for a compact Qwen3 dense checkpoint.
// Every small Qwen3 model shares the same vLLM launch shape, so we synthesise
// the Config to cut down on repetition.
func qwenSmallDense(id, name, modelID string, minVRAMGB float64) Config {
	return Config{
		ID:       id,
		Name:     name,
		Workload: WorkloadVLLM,
		ModelID:  modelID,
		Image:    imageVLLMStable,
		Port:     "8000",
		ExtraArgs: strings.Join([]string{
			"--trust-remote-code",
			"--tensor-parallel-size 1",
			"--max-model-len 32768",
			"--reasoning-parser qwen3",
		}, " "),
		Volumes:         hfMountDefault,
		Runtime:         runtimeDefault,
		Description:     name + " — single-GPU default.",
		Source:          "vllm-project/recipes Qwen/Qwen3.md",
		TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
		MinVRAMGBPerGPU: minVRAMGB,
		MinGPUCount:     1,
		Quantization:    QuantBF16,
		Arch:            ArchHopper,
	}
}
