package bkc

import "strings"

func init() {
	register(
		// MiniMax-M2.7 (4x TP default).
		Config{
			ID:       "minimax-m2-tp4",
			Name:     "MiniMax-M2.7 (TP4)",
			Workload: WorkloadVLLM,
			ModelID:  "MiniMaxAI/MiniMax-M2.7",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 4",
				"--tool-call-parser minimax_m2",
				"--reasoning-parser minimax_m2",
				"--compilation-config " + `'{"mode":3,"pass_config":{"fuse_minimax_qk_norm":true}}'`,
				"--enable-auto-tool-choice",
				"--trust-remote-code",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "MiniMax-M2.7 on 4x H100/H200/B200 with MiniMax QK-norm fusion.",
			Source:          "vllm-project/recipes MiniMax/MiniMax-M2.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// MiMo-V2-Flash (Xiaomi).
		Config{
			ID:       "mimo-v2-flash-tp4",
			Name:     "MiMo V2 Flash (TP4)",
			Workload: WorkloadVLLM,
			ModelID:  "XiaomiMiMo/MiMo-V2-Flash",
			Image:    imageVLLMStable,
			Port:     "9001",
			ExtraArgs: strings.Join([]string{
				"--host 0.0.0.0",
				"--seed 1024",
				"--served-model-name mimo_v2_flash",
				"--tensor-parallel-size 4",
				"--trust-remote-code",
				"--gpu-memory-utilization 0.9",
				"--tool-call-parser qwen3_xml",
				"--reasoning-parser qwen3",
				"--generation-config vllm",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "XiaomiMiMo V2 Flash on 4x Hopper/Blackwell with Qwen3-XML tool parser.",
			Source:          "vllm-project/recipes MiMo/MiMo-V2-Flash.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 40,
			MinGPUCount:     4,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// ByteDance Seed-OSS-36B Instruct.
		Config{
			ID:       "seed-oss-36b-instruct-tp8",
			Name:     "Seed-OSS 36B Instruct (TP8)",
			Workload: WorkloadVLLM,
			ModelID:  "ByteDance-Seed/Seed-OSS-36B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--host localhost",
				"--tensor-parallel-size 8",
				"--enable-auto-tool-choice",
				"--tool-call-parser seed_oss",
				"--trust-remote-code",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "ByteDance Seed-OSS 36B on 8x Hopper/Blackwell.",
			Source:          "vllm-project/recipes Seed/Seed-OSS-36B.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Intern-S1 BF16 on 8x H800.
		Config{
			ID:       "intern-s1-bf16",
			Name:     "Intern-S1 BF16",
			Workload: WorkloadVLLM,
			ModelID:  "internlm/Intern-S1",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 8",
				"--enable-auto-tool-choice",
				"--reasoning-parser deepseek_r1",
				"--tool-call-parser internlm",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Intern-S1 BF16 on 8x H800/H100 with DeepSeek-R1 reasoning parser.",
			Source:          "vllm-project/recipes InternLM/Intern-S1.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Intern-S1 FP8 on 4x H800.
		Config{
			ID:       "intern-s1-fp8-tp4",
			Name:     "Intern-S1 FP8 (TP4)",
			Workload: WorkloadVLLM,
			ModelID:  "internlm/Intern-S1-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 4",
				"--enable-auto-tool-choice",
				"--reasoning-parser deepseek_r1",
				"--tool-call-parser internlm",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Intern-S1 FP8 on 4x H100/H200/B200.",
			Source:          "vllm-project/recipes InternLM/Intern-S1.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// InternVL 3.5 8B.
		Config{
			ID:       "internvl-3-5-8b",
			Name:     "InternVL 3.5 8B",
			Workload: WorkloadVLLM,
			ModelID:  "OpenGVLab/InternVL3_5-8B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "InternVL 3.5 8B single-GPU default.",
			Source:          "vllm-project/recipes InternVL/InternVL3_5.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 20,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Jina Reranker m0.
		Config{
			ID:       "jina-reranker-m0",
			Name:     "Jina Reranker m0",
			Workload: WorkloadVLLM,
			ModelID:  "jinaai/jina-reranker-m0",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--host 0.0.0.0",
				"--tensor_parallel_size 2",
				"--gpu-memory-utilization 0.75",
				"--max_num_seqs 32",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Jina Reranker m0 — 2-way TP reranker server.",
			Source:          "vllm-project/recipes Jina/Jina-reranker-m0.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 24,
			MinGPUCount:     2,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Arcee Trinity Large Thinking BF16.
		Config{
			ID:       "arcee-trinity-large-thinking",
			Name:     "Arcee Trinity Large Thinking",
			Workload: WorkloadVLLM,
			ModelID:  "arcee-ai/Trinity-Large-Thinking",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--dtype bfloat16",
				"--reasoning-parser deepseek_r1",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
				"--tensor-parallel-size 1",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Arcee Trinity Large Thinking single-GPU default (BF16).",
			Source:          "vllm-project/recipes ArceeAI/Trinity-Large-Thinking.md",
			TargetDevices:   []string{DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 60,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Hunyuan A13B Instruct (TP2).
		Config{
			ID:       "hunyuan-a13b-instruct",
			Name:     "Hunyuan A13B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "tencent/Hunyuan-A13B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 2",
				"--trust-remote-code",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Tencent Hunyuan A13B Instruct on 2x Hopper/Blackwell.",
			Source:          "vllm-project/recipes Tencent-Hunyuan/Hunyuan-Instruct.md",
			TargetDevices:   []string{DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     2,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// HunyuanOCR.
		Config{
			ID:       "hunyuan-ocr",
			Name:     "HunyuanOCR",
			Workload: WorkloadVLLM,
			ModelID:  "tencent/HunyuanOCR",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--no-enable-prefix-caching",
				"--mm-processor-cache-gb 0",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "HunyuanOCR compact vision-language OCR model.",
			Source:          "vllm-project/recipes Tencent-Hunyuan/HunyuanOCR.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10, DeviceJetsonThor},
			MinVRAMGBPerGPU: 16,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// StepFun Step-3.5-Flash.
		Config{
			ID:       "step-3-5-flash",
			Name:     "Step-3.5-Flash",
			Workload: WorkloadVLLM,
			ModelID:  "stepfun-ai/Step-3.5-Flash",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 4",
				"--reasoning-parser step3p5",
				"--tool-call-parser step3p5",
				"--enable-auto-tool-choice",
				"--trust-remote-code",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "StepFun Step-3.5-Flash on 4x Hopper/Blackwell.",
			Source:          "vllm-project/recipes StepFun/Step-3.5-Flash.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Ring-1T-FP8 (inclusionAI) 8x H200/B200.
		Config{
			ID:       "ring-1t-fp8",
			Name:     "Ring-1T FP8",
			Workload: WorkloadVLLM,
			ModelID:  "inclusionAI/Ring-1T-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 8",
				"--gpu-memory-utilization 0.9",
				"--max_num_seqs 32",
				"--kv-cache-dtype fp8",
				"--served-model-name Ring-1T-FP8",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "inclusionAI Ring-1T FP8 on 8x H200/B200.",
			Source:          "vllm-project/recipes inclusionAI/Ring-1T-FP8.md",
			TargetDevices:   []string{DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 141,
			MinGPUCount:     8,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Ernie 4.5 21B A3B.
		Config{
			ID:       "ernie-4-5-21b-a3b",
			Name:     "Ernie 4.5 21B A3B",
			Workload: WorkloadVLLM,
			ModelID:  "baidu/ERNIE-4.5-21B-A3B-PT",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 1",
				"--trust-remote-code",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Ernie 4.5 21B A3B — single-GPU default.",
			Source:          "vllm-project/recipes Ernie/Ernie4.5.md",
			TargetDevices:   []string{DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 64,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Ernie 4.5 300B A47B FP8.
		Config{
			ID:       "ernie-4-5-300b-a47b-fp8",
			Name:     "Ernie 4.5 300B A47B FP8",
			Workload: WorkloadVLLM,
			ModelID:  "baidu/ERNIE-4.5-300B-A47B-PT",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 8",
				"--gpu-memory-utilization=0.95",
				"--quantization fp8",
				"--trust-remote-code",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Ernie 4.5 300B A47B with online FP8 quant on 8x 80 GB GPUs.",
			Source:          "vllm-project/recipes Ernie/Ernie4.5.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Ernie 4.5 VL 28B A3B.
		Config{
			ID:       "ernie-4-5-vl-28b-a3b",
			Name:     "Ernie 4.5 VL 28B A3B",
			Workload: WorkloadVLLM,
			ModelID:  "baidu/ERNIE-4.5-VL-28B-A3B-PT",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Ernie 4.5 VL 28B A3B — single-GPU multimodal default.",
			Source:          "vllm-project/recipes Ernie/Ernie4.5-VL.md",
			TargetDevices:   []string{DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 64,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Ernie 4.5 VL 424B A47B FP8 w/ CPU offload.
		Config{
			ID:       "ernie-4-5-vl-424b-a47b-fp8-offload",
			Name:     "Ernie 4.5 VL 424B A47B FP8 (CPU offload)",
			Workload: WorkloadVLLM,
			ModelID:  "baidu/ERNIE-4.5-VL-424B-A47B-PT",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 8",
				"--quantization fp8",
				"--cpu-offload-gb 50",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Ernie 4.5 VL 424B A47B on 8x 80 GB with 50 GB CPU offload.",
			Source:          "vllm-project/recipes Ernie/Ernie4.5-VL.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceA100_80},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// PaddleOCR-VL.
		Config{
			ID:       "paddleocr-vl",
			Name:     "PaddleOCR-VL",
			Workload: WorkloadVLLM,
			ModelID:  "PaddlePaddle/PaddleOCR-VL",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--max-num-batched-tokens 16384",
				"--no-enable-prefix-caching",
				"--mm-processor-cache-gb 0",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "PaddleOCR-VL single-GPU default.",
			Source:          "vllm-project/recipes PaddlePaddle/PaddleOCR-VL.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10, DeviceJetsonThor},
			MinVRAMGBPerGPU: 16,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},
	)
}
