package bkc

import "strings"

func init() {
	register(
		Config{
			ID:       "nemotron-3-super-nvfp4",
			Name:     "Nemotron 3 Super NVFP4",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4",
			Image:    "vllm/vllm-openai:v0.17.0-cu130",
			Port:     "8888",
			ExtraArgs: strings.Join([]string{
				"--tokenizer nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4",
				"--served-model-name nemotron-3-super-nvfp4",
				"--tensor-parallel-size 1",
				"--gpu-memory-utilization 0.90",
				"--max-model-len 262144",
				"--max-num-seqs 8",
				"--max-num-batched-tokens 16384",
				"--kv-cache-dtype fp8",
				"--enable-prefix-caching",
				"--enable-chunked-prefill",
				"--trust-remote-code",
			}, " "),
			Env: map[string]string{
				"VLLM_ATTENTION_BACKEND":     "FLASHINFER",
				"VLLM_NVFP4_GEMM_BACKEND":    "marlin",
				"VLLM_TEST_FORCE_FP8_MARLIN": "1",
				"VLLM_MARLIN_USE_ATOMIC_ADD": "1",
				"VLLM_FP8_BACKEND":           "marlin",
				"VLLM_SCALED_MM_BACKEND":     "marlin",
			},
			Volumes:         hfMountDefault,
			Plugins:         []string{"vllm-reasoning-parser-super-v3"},
			Runtime:         runtimeDefault,
			Description:     "Best known vLLM config derived from the local vllm-model-template for Nemotron Super.",
			Source:          "~/genai/vllm-model-template/.envrc",
			TargetDevices:   []string{DeviceRTXPRO6000, DeviceB200, DeviceH200, DeviceH100_94},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Prefills image, port, core vLLM flags, and required runtime env vars.",
				"Includes a persistent Hugging Face cache mount so weights are reused on the host.",
				"Adds the Super V3 reasoning parser plugin and matching runtime settings.",
			},
		},

		// Nemotron-3-Nano-Omni-30B-A3B-Reasoning NVFP4 — multimodal (video/audio/image/text)
		// vLLM config for single-GPU Blackwell deployments.
		Config{
			ID:       "nemotron-3-nano-omni-30b-a3b-reasoning-nvfp4",
			Name:     "Nemotron 3 Nano Omni 30B A3B Reasoning NVFP4",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-NVFP4",
			Image:    imageVLLM020Audio,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
				"--max-model-len 131072",
				"--max-num-seqs 384",
				"--video-pruning-rate 0.5",
				"--allowed-local-media-path /",
				`--media-io-kwargs {"video":{"fps":2,"num_frames":256}}`,
				"--reasoning-parser nemotron_v3",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
				"--kv-cache-dtype fp8",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "NVIDIA Nemotron-3-Nano-Omni-30B-A3B-Reasoning NVFP4 vLLM config for multimodal Blackwell inference with audio dependencies preinstalled.",
			Source:          "https://huggingface.co/nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-NVFP4",
			TargetDevices:   []string{DeviceRTX5090, DeviceRTXPRO6000, DeviceB200},
			MinVRAMGBPerGPU: 32,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Uses a vLLM 0.20.0-derived image with vllm[audio] preinstalled for audio inputs and videos with audio tracks.",
				"Uses NVIDIA's general 128K-context vLLM launch recipe, FP8 KV cache, nemotron_v3 reasoning parser, and Qwen3 Coder tool-call parser.",
				"NVFP4 weights are about 21 GB; use the separate GB10 / DGX Spark BKC for Spark-specific memory settings.",
			},
		},

		// DGX Spark / GB10 variant of the Nano Omni NVFP4 checkpoint.
		Config{
			ID:       "nemotron-3-nano-omni-30b-a3b-reasoning-nvfp4-gb10",
			Name:     "Nemotron 3 Nano Omni 30B A3B Reasoning NVFP4 (GB10 / DGX Spark)",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-NVFP4",
			Image:    imageVLLM020Audio,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--served-model-name nemotron_3_nano_omni",
				"--max-model-len 131072",
				"--max-num-seqs 8",
				"--gpu-memory-utilization 0.8",
				`--limit-mm-per-prompt {"video":1,"image":1,"audio":1}`,
				`--media-io-kwargs {"video":{"fps":2,"num_frames":256}}`,
				"--allowed-local-media-path /",
				"--enable-prefix-caching",
				"--max-num-batched-tokens 32768",
				"--reasoning-parser nemotron_v3",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
				"--kv-cache-dtype fp8",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "DGX Spark / GB10 vLLM deployment of Nemotron-3-Nano-Omni-30B-A3B-Reasoning NVFP4 with audio dependencies preinstalled.",
			Source:          "https://huggingface.co/nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-NVFP4",
			TargetDevices:   []string{DeviceGB10},
			MinVRAMGBPerGPU: 32,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Uses NVIDIA's DGX Spark vLLM recipe with lower concurrency and explicit multimodal limits to avoid the generic 384-sequence launch on GB10.",
				"The vLLM 0.20.0-derived image must include vllm[audio] because Spark audio/video-audio use cases require audio extras before vLLM starts.",
				"If Spark runs out of unified memory, reduce --gpu-memory-utilization toward 0.70 or lower --max-model-len toward 32768.",
			},
		},

		// Nemotron-3-Nano-30B-A3B FP8 — fits single GPU >= 40 GB (H100 80 GB,
		// H200, B200, RTX PRO 6000, GB10 via NGC container).
		Config{
			ID:       "nemotron-3-nano-30b-a3b-fp8",
			Name:     "Nemotron 3 Nano 30B A3B FP8",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--async-scheduling",
				"--kv-cache-dtype fp8",
				"--tensor-parallel-size 1",
				"--max-model-len 262144",
				"--max-num-seqs 8",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
			}, " "),
			Env: map[string]string{
				"VLLM_USE_FLASHINFER_MOE_FP8": "1",
				"VLLM_FLASHINFER_MOE_BACKEND": "throughput",
			},
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "NVIDIA Nemotron-3-Nano-30B-A3B FP8 for single-GPU Blackwell / Hopper deployments.",
			Source:          "vllm-project/recipes NVIDIA/Nemotron-3-Nano-30B-A3B.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH100_94, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 48,
			MinGPUCount:     1,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
			Notes: []string{
				"Uses FlashInfer FP8 MoE (throughput-tuned) as recommended in the NVIDIA recipe.",
				"Enables the Qwen3-style tool-call parser for function calling.",
			},
		},

		// Nemotron-3-Nano-30B-A3B BF16 — needs ~60 GB, fits single H100 80 GB, H200, B200, or GB10 unified memory.
		Config{
			ID:       "nemotron-3-nano-30b-a3b-bf16",
			Name:     "Nemotron 3 Nano 30B A3B BF16",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--async-scheduling",
				"--tensor-parallel-size 1",
				"--max-model-len 262144",
				"--max-num-seqs 8",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "NVIDIA Nemotron-3-Nano-30B-A3B BF16 for single-GPU Hopper/Blackwell deployments.",
			Source:          "vllm-project/recipes NVIDIA/Nemotron-3-Nano-30B-A3B.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 72,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
			Notes: []string{
				"BF16 variant keeps full-precision accuracy at the cost of ~60 GB VRAM.",
				"On DGX Spark GB10 use the NGC container (nvcr.io/nvidia/vllm:25.12.post1-py3).",
			},
		},

		// GB10 (DGX Spark) — aarch64 NGC container recommended by NVIDIA.
		Config{
			ID:       "nemotron-3-nano-30b-a3b-bf16-gb10",
			Name:     "Nemotron 3 Nano 30B A3B BF16 (GB10 / DGX Spark)",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
			Image:    imageVLLMNGC,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
				"--max-model-len 262144",
				"--max-num-seqs 8",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
				"--reasoning-parser-plugin nano_v3_reasoning_parser.py",
				"--reasoning-parser nano_v3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "DGX Spark (GB10) BF16 deployment of Nemotron-3-Nano-30B-A3B.",
			Source:          "vllm-project/recipes NVIDIA/Nemotron-3-Nano-30B-A3B.md",
			TargetDevices:   []string{DeviceGB10},
			MinVRAMGBPerGPU: 72,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Uses the NGC aarch64 vLLM container built for DGX Spark.",
				"Loads the nano_v3 reasoning parser shipped with the BF16 checkpoint.",
			},
		},

		// Jetson Thor (aarch64) variant of the Nano BF16 checkpoint.
		Config{
			ID:       "nemotron-3-nano-30b-a3b-bf16-jetson-thor",
			Name:     "Nemotron 3 Nano 30B A3B BF16 (Jetson Thor)",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
			Image:    imageVLLMJetson,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
				"--max-model-len 262144",
				"--max-num-seqs 8",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
				"--reasoning-parser-plugin nano_v3_reasoning_parser.py",
				"--reasoning-parser nano_v3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Jetson Thor BF16 deployment of Nemotron-3-Nano-30B-A3B.",
			Source:          "vllm-project/recipes NVIDIA/Nemotron-3-Nano-30B-A3B.md",
			TargetDevices:   []string{DeviceJetsonThor},
			MinVRAMGBPerGPU: 72,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Uses the NVIDIA-provided Jetson Thor vLLM image from GHCR.",
			},
		},

		// Nemotron-Nano-12B-v2-VL BF16 — small multimodal model.
		Config{
			ID:       "nemotron-nano-12b-v2-vl-bf16",
			Name:     "Nemotron Nano 12B v2 VL BF16",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-BF16",
			Image:    imageVLLMNGC,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
				"--max-model-len 131072",
				"--served-model-name nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-BF16",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Compact BF16 vision-language Nemotron fitting a single data-centre or workstation GPU.",
			Source:          "vllm-project/recipes NVIDIA/Nemotron-Nano-12B-v2-VL.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceA100_80, DeviceGB10},
			MinVRAMGBPerGPU: 32,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
			Notes: []string{
				"NVIDIA recommends the 25.12 NGC container or a nightly vLLM 0.12+ build.",
			},
		},

		// Nemotron-Nano-12B-v2-VL FP8.
		Config{
			ID:       "nemotron-nano-12b-v2-vl-fp8",
			Name:     "Nemotron Nano 12B v2 VL FP8",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-FP8",
			Image:    imageVLLMNGC,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--kv-cache-dtype fp8",
				"--tensor-parallel-size 1",
				"--max-model-len 131072",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "FP8 vision-language Nemotron tuned for single-GPU Blackwell / Hopper inference.",
			Source:          "vllm-project/recipes NVIDIA/Nemotron-Nano-12B-v2-VL.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceL40S, DeviceGB10},
			MinVRAMGBPerGPU: 24,
			MinGPUCount:     1,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Nemotron-Nano-12B-v2-VL NVFP4 (QAD).
		Config{
			ID:       "nemotron-nano-12b-v2-vl-nvfp4",
			Name:     "Nemotron Nano 12B v2 VL NVFP4 (QAD)",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-NVFP4-QAD",
			Image:    imageVLLMNGC,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--kv-cache-dtype fp8",
				"--tensor-parallel-size 1",
				"--max-model-len 131072",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "NVFP4 Blackwell-optimised vision-language Nemotron, ~8 GB weights.",
			Source:          "vllm-project/recipes NVIDIA/Nemotron-Nano-12B-v2-VL.md",
			TargetDevices:   []string{DeviceB200, DeviceRTXPRO6000, DeviceGB10, DeviceRTX5090},
			MinVRAMGBPerGPU: 16,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
		},
	)
}
